CREATE DATABASE GentalCareDental
GO

USE GentalCareDental
GO

CREATE TABLE Account
(
	UserID NVARCHAR(10) PRIMARY KEY,
	UserName NVARCHAR(50) NOT NULL,
	UserPassword NVARCHAR(50) NOT NULL,
	UserEmail NVARCHAR(50) NOT NULL,
	DateOfBirth DATE NULL,
	UserAddress NVARCHAR(150) NULL,
	UserPhone NVARCHAR(11) NOT NULL,
	Gender NVARCHAR(1) NOT NULL,
	ImageAvatar VARBINARY(MAX) NULL,
	ColorAvatar NVARCHAR(10) NULL,
	DefaultAvatar CHAR(1),
	UserRole INT DEFAULT '0',
	AccountCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
	UserStatus bit NOT NULL
)

CREATE TABLE Notify
(
	NotifyID NVARCHAR(10) PRIMARY KEY,
	UserID NVARCHAR(10) FOREIGN KEY REFERENCES Account(UserID)  NOT NULL,
	NotifyType NVARCHAR(10) NOT NULL,
	NotifyCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
	NotifyStatus BIT NOT NULL
)

CREATE TABLE Employee
(
	EmployeeID NVARCHAR(10) PRIMARY KEY,
	Salary INT NOT NULL,
	Insurance INT NOT NULL,
	UserID NVARCHAR(10) FOREIGN KEY REFERENCES Account(UserID),
	Status BIT NOT NULL
)

CREATE TABLE RoomChat
(
	RoomID NVARCHAR(10) PRIMARY KEY,
	EmployeeID NVARCHAR(10) FOREIGN KEY REFERENCES Employee(EmployeeID) NOT NULL,
	UserID NVARCHAR(10) FOREIGN KEY REFERENCES Account(UserID) NOT NULL,
	RoomStatus BIT NOT NULL
)

CREATE TABLE MessageChat
(
	ChatID NVARCHAR(10) PRIMARY KEY,
	RoomID NVARCHAR(10) FOREIGN KEY REFERENCES RoomChat(RoomID) NOT NULL,
	ChatContent NVARCHAR(MAX) NOT NULL,
	ChatDate DATETIME DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE Hospital
(
	HospitalID NVARCHAR(10) PRIMARY KEY,
	HospitalName NVARCHAR(150) NOT NULL,
	HospitalPhone NVARCHAR(10) NOT NULL,
	HospitalAddress NVARCHAR(150) NOT NULL,
	HospitalStatus BIT NOT NULL,
)

CREATE TABLE ServiceType
(
	ServiceTypeID NVARCHAR(10) PRIMARY KEY,
	ServiceTypeName NVARCHAR(150) NOT NULL,
)

CREATE TABLE Slot
(
	SlotID INT IDENTITY(1,1) PRIMARY KEY,
	SlotStart TIME NOT NULL,
	SlotEnd TIME NOT NULL,
	SlotStatus BIT NOT NULL
)

CREATE TABLE Services
(
	ServiceID NVARCHAR(10) PRIMARY KEY,
	ServiceName NVARCHAR(150) NOT NULL,
	ServicePrice INT,
	ImageService VARBINARY(MAX),
	DescriptionService NTEXT NOT NULL,
	ServiceStatus BIT NOT NULL,
	ServiceTypeID NVARCHAR(10) FOREIGN KEY REFERENCES ServiceType(ServiceTypeID) NOT NULL,
)

CREATE TABLE ServiceSlot
(
	SlotServiceID NVARCHAR(10) PRIMARY KEY,
	SlotStart TIME NOT NULL,
	SlotEnd TIME NOT NULL,
	SlotStatus BIT NOT NULL,
	ServiceID NVARCHAR(10) FOREIGN KEY REFERENCES Services(ServiceID) NOT NULL,
	SlotID INT FOREIGN KEY REFERENCES Slot(SlotID) NOT NULL

)

CREATE TABLE Booking
(
	BookingID NVARCHAR(10) PRIMARY KEY,
	UserID NVARCHAR(10) FOREIGN KEY REFERENCES Account(UserID) NOT NULL,
	HospitalID NVARCHAR(10) FOREIGN KEY REFERENCES Hospital(HospitalID) NOT NULL,
	BookingNote NVARCHAR(Max),
	BookingCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
	BookingStatus BIT NOT NULL,
)

CREATE TABLE BookingService
(
	BookingServiceID NVARCHAR(10) PRIMARY KEY,
	ServiceID NVARCHAR(10) FOREIGN KEY REFERENCES Services(ServiceID) NOT NULL,
	BookingID NVARCHAR(10) FOREIGN KEY REFERENCES Booking(BookingID) NOT NULL,
	SlotServiceID NVARCHAR(10) FOREIGN KEY REFERENCES ServiceSlot(SlotServiceID)  NOT NULL,
	BookingDate date NOT NULL, 
	BSStatus BIT NOT NULL

)

CREATE TABLE FeedBack
(
	FeedBackID NVARCHAR(10) PRIMARY KEY,
	BookingServiceID NVARCHAR(10) FOREIGN KEY REFERENCES BookingService(BookingServiceID) NOT NULL,
	NumberRating INT,
	FeedBackContent NVARCHAR(MAX),
	FeedBackCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
	FeedBackStatus BIT NOT NULL
)
